version: '3.8'
services:
  frontend:
    build: ./frontend/textbook-exchange-app
    container_name: frontend
    restart: always

  backend:
    build: ./backend
    container_name: backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email jacksonwaffle1@gmail.com --agree-tos --no-eff-email -d waffledev.me -d api.waffledev.me
