services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - 80

  frontend:
    build: ./frontend/textbook-exchange-app
    container_name: frontend
    expose:
      - 80

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
