services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - 80

  frontend:
    build: ./frontend/textbook-exchange-app
    container_name: frontend
    expose:
      - 80
